### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by krizhanovsky** [tempesta-tech/tempesta#309]
The initial implementation of [HTTP/2](https://tools.ietf.org/html/rfc7540) was done in https://github.com/tempesta-tech/tempesta/pull/1176 . Need a review and further development of the code. I suggest to create a new pull request instead of developing #1176.

Consider [Cache Digests](http://mnot.github.io/I-D/h2-cache-digest/) as important for [Ideal HTTP Performance](https://www.mnot.net/blog/2016/04/22/ideal-http). 

There is [HTTP/2 test suite](https://github.com/http2/http2-test) which should be used to test the implementation.

Context of the issue is just a **robust and performance** architecture of HTTP/2 (with #687 in mind - we should not let similar issues to pass to the master and probably there will be cheap (quick) opportunities to fix some of #687 problems). All the small extensions, protocol features and bugs should be reported in **small** separate tasks.

An minimal requirement for the issue to be done is that a HTTP/2 capable browser must be able to load tempesta-tech.com via HTTP/2.

## QUIC foundations

Some of HTTP/2 mechanisms are moved to QUIC (#724): streams, frames, compression. So please make required TODO comments and necessary code adjustments for further extensions to QUIC. In particular at least these docs affect current HTTP/2 design:

- [QUIC](https://www.ietf.org/id/draft-ietf-quic-transport-18.txt) transport defines main primitives of QUIC.

- [QPACK](https://www.ietf.org/id/draft-ietf-quic-qpack-06.txt) for HPACK. Probably Avoiding Head-of-Line Blocking is the most influential feature of QPACK which affect synchronization design of HTTP/2 streams and maybe more connection-wide attributes.

- [HTTP/3](https://www.ietf.org/id/draft-ietf-quic-http-18.txt) for the whole new code. Chapters 4 and A.2 discuss similarities and differences in the framing layers.

## Notes

We should not support Huffman encoding, see https://github.com/tempesta-tech/tempesta/pull/1176#discussion_r257789810 . Huffman decoding is only required now. However, in #1125 we'll generate HTTP/2 requests and Huffman encoding [does make difference](https://www.mnot.net/blog/2018/11/27/header_compression) for HTTP headers. So I'd leave current Huffman encoding in the source code, but leave it unused until #1125.

Unfortunately we can not pass Huffman-encoded strings to HTTP parser because upper and lower case characters with different umber of bits and have not clear transition (like 0x20 for base ASCII). So we have to decode HTTP headers before passing them to HTTP parser.

### HTTP/2 amplification threat

HTTP/2 HPACK introduces [HTTP/2 amplification threat](https://pure.qub.ac.uk/portal/files/138103125/dbeckett_ssezer_Paper_Tsunami_Final.pdf). Protection against the attack is left for #488.

## Framing

HTTP/2 (QUIC) uses very close, but still different in many details, frames (see [QUIC transport](https://www.ietf.org/id/draft-ietf-quic-transport-18.txt) chapter 12 and [HTTP/3](https://www.ietf.org/id/draft-ietf-quic-http-18.txt) chapters 4 and A.2 ), so it seems we can not just reuse the code, but, probably, some logic us reusable.

Anyway the logic is relatively complex and defines a logical layer, so I propose to develop it in a new source code file (logic module) `http_frame.c` which later can be split for HTTP/2- and HTTP/3- specific code.

Since max frame size is 16MB, should call the decoder layer on each frame chunk except if there is not enough payload for processing.

The framing layer determines type of frames: service, headers, body. Header frame payload should go through the decoder layer while body (data) frame payload should skip the decoder and go to HTTP parser directly. The parser code must be split to handle body and headers separately. Service frames must manage current stream state and don't imply HTTP parser calling.

## Streams

An HTTP/2 or HTTP/3 stream is essentially FSM with the defines state transitions. A stream and frame type must be passed to `tfw_http_req_process()`. If we define stream with `TfwStream` data structure, then `TfwStream->parser` should replace current `TfwConn->parser`.

I propose to use 128 for `SETTINGS_MAX_CONCURRENT_STREAMS` and handle the streams in a binary heap storing identifiers and pointers to dynamically allocated stream descriptors. Maybe there is a better data structure.

Flow control should be left until #498 and now we should announce the largest possible window and ignore the client window - just send the whole response to a client. Keeping the response in Tempesta memory and send it in small chunks may lead to significant security flaw. It's bad to ignore the client window, so #498 was marked as crucial and moved to the next milestone.

Streams prioritization and dependency is the subject for #1196.

All in all the stream logic implies relatively complex logic about flow control, prioritization and so on, so I propose also to move it to a new `http_stream.c`. Control stream(s) logic, in sense of frames mentioned below, must be handled also here by calling appropriate HTTP, framing, and connection routines. Note stream operation in HTTP/3 described in https://tools.ietf.org/html/draft-ietf-quic-transport-18#section-2 and https://tools.ietf.org/html/draft-ietf-quic-http-18#section-3 as well.

Only `HEADERS`, `DATA`, `CONTINUATION`, `RST_STREAM`, `PING`, `GOAWAY` frames must be implemented in this issue, probably `SETTINGS` also should be supported for some cases. A client [nevere sends](https://tools.ietf.org/html/rfc7540#section-8.2.1) `PUSH_PROMISE` frame, so it's implementation is left for #1194. `WINDOW_UPDATE` frame is left for #498.

## HTTP/2 <-> HTTP/1.1 message transformation

I propose to extend `TfwHttpHdrTbl` that it can contain plain HTTP/1.1 header strings as well as indexes to to encoded HTTP/2 headers. The interfaces to the current table should be generalized in such way that all the logic can get necessary information about a header regardless whether it's HPACK encoded or in plain TfwStr format.

However, if `TfwHttpHdrTbl` we can handle Huffman-decoded only headers.

Note that HTTP/2 defines message length in other ways than HTTP/1.1, so current chunked, `Content-Length` and connection close logic must be adusted.

### Decoder layer

The HTTP parser function must call from a new decoder layer. The decoder layer must be aware about HTTP parser states and feed current decoded chunk to the parser. The decoder should be responsible for:
1. HPACK index decoding (only part (value) of an HTTP header may be fed to the parser)
2. Huffman decoding
3. HTTP normalization #2 .

We should take advantage from the bit string translation to a characters string. In particular, the should be multiple Huffman decoding tables implementing [characters filtration](https://github.com/tempesta-tech/tempesta/wiki/HTTP-security#custom-character-sets) (just return error for particular bits mapping to a prohibited character). Next the Huffman decoding state machine can be generated in such way that for example `010101 00000 100001` will be immediately blocked or translated to a space ` ` (the bit string means `%0A`, `\n`). There is no need to implement any functionality of #2, but the decoder must be designed in appropriate. (In #2 we can add support for run-time updated Huffman decoder table to support reconfiguration of the translation tables). However, current alphabets checking must be implemented for HTTP/2 using Huffman decoder. Also, please remove `http_norm.h` and all the related stuff.

The decoder must receive a chunk of data, execute the decoding logic, for an encoded string if any and call the parser for the string. In this case the parser will have many entries so #1131 is crucial now.  

The decoder must write data to a new HTTP request because decoded data is usually larger than original.

In general case Humman-encoded symbol can cross byte bounds, so the decoder FSM must store some context data to be able to process frame chunks passed from the framing layer.

### HTTP parser

The parser must eat HTTP/1.1 and HTTP/2 messages depending on information from the framing/streaming layer, HTTP/2 path must be in preference (in sense of conditions and `likely` paths). This is required since HTTP/2 headers use binary separators instead of CRLF.

It's also possible to process the binary delimiters on decoder side (after all the delimeters determine type of current header - indexed, encoded, or plain) and left current HTTP parser to process ASCII parts of the headers only.

`tfw_http_parse_req()` must be split into method, URI, HTTP version, headers, and body parsing parts. Only some of the parts must be called for HTTP/2.

[Characters filtration](https://github.com/tempesta-tech/tempesta/wiki/HTTP-security#custom-character-sets), the SIMD alphabets checking, must not be executed for HTTP/2 strings since we have Huffman decoders.

### Headers conversion

Headers adjustments, `tfw_http_adjust_{req,resp}()` are the right place to convert headers for different format (from/to HTTP/2 to/from HTTP/1.1). They're also good for this because of #1103 and whe need/have extra space for the format conversion and changing the headers.

Responses should be encoded in-place (they're always smaller than HTTP/1.1) in `tfw_http_adjust_resp()` leaving more optimization opportunities for #1103. The new added headers must be immediately compressed in-place, so HTTP XFRM logic must be adjusted for HTTP/2 (create HPACK'ed headers instead of compress plain strings added by the current logic).

### Caching

It'd be good to keep HTTP/2 and HTTP/1.1 headers in cached entries, but now it's not necessary and we can translare HTTP/1.1 headers to HTTP/2 in `tfw_http_adjust_resp()`.

## TODO

The code must be done in separate branches producing many sequential small PRs which of them must go through a review and be merged into the master. It's easier to review a smaller code and we can catch issues earlier. Also this way we can avoid heavy rebases. I suggest to split PRs in the way that there are not more than 1 of the tasks below in a PR.

- [x] **Framing** decoding. In general, framing layer should be hooked the same way as TLS and current HTTP layers. It's not necessary to use GFSM, but it might be useful to handle data offsets. Current `tfw_http_req_process()` handles the message parsing and it's processing logic (scheduling, caching etc.) and this can remain - different HTTP/2 frames can be treated by the function just as separate chunks. However, from framing layer we know exact type of current frame and we should call the right (headers or body) parser instead of analyzing current parsing state.

- [x] **Starting HTTP/2** (RFC 7540 chapter 3): [ALPN handling](https://github.com/tempesta-tech/tempesta/pull/1176#discussion_r257460195), initial transmission of 101 (Switching protocols) response and parsing the client preface.

- [x] **Stream** FSMs handling. At this stage functional test for `PING` frame must work.

- [x] **HTTP/2 <-> HTTP/1.1 message transformation** to transfer messages between HTTP/2 clients and HTTP/1.1 backends.

- [x] **HPACK** and Huffman logic.

- [x] **HTTP/1.1 response streaming for pipelined requests** - with HTTP/2 we don't have blocking requests any more, so each received response can be forwarded to a client immediately. So it seems `seq_queue` becomes HTTP/1.1 specific and in context of #687 it'd be good to not to use it for HTTP/2 at all.

- [ ] Update the Wiki list of [known implementations of HTTP/2](https://github.com/http2/http2-spec/wiki/Implementations).

**Comment by krizhanovsky** [comment]
The protocol is [doubtful](https://www.varnish-cache.org/docs/trunk/phk/http20.html), Nginx team also has shown cases at HighLoad++'15 where HTTP/2 delivers relatively poor performance. So postpone the task to 0.6 release or at least real user requests.

**Comment by krizhanovsky** [comment]
We've got the request, so schedule it back to 0.5.

**Comment by krizhanovsky** [comment]
The initial implementation of HTTP/2 was done in https://github.com/tempesta-tech/tempesta/pull/1176 . Need a review of the code.

Context of the issue is just a **robust and performance** architecture of HTTP/2 (with #687 in mind - we should not let similar issues to pass to the master and probably there will be cheap (quick) opportunities to fix some of #687 problems). All the small extensions, protocol features and bugs should be reported in **small** separate tasks.

An minimal requirement for the issue to be done is that a HTTP/2 capable browser must be able to load tempesta-tech.com via HTTP/2.

**Comment by aleksostapenko** [comment]
### HTTP/2 layers overview
1. Layers UP flow order:
-> TLS
-> Framing (1. Incorporated with Stream FSM and Stream Scheduler, to be faster processed on Stream ID determination and determination dependent Streams as well as errors with incorrect FSM states etc., before decoding/processing the frame payload; 2. After passing through Stream FSM and Stream Scheduler, the further processing depends on the type of frame: a) service frames should not be passed to upper layers; b) HEADERS frames' payload must be passed to Decoder at first, and then - to HTTP parser; c) DATA frames' payload must be passed to HTTP parser directly);
-> Decoder FSM (must be called on each skb for HEADERS frames' payload);
-> HTTP Parser (must be called on each skb for DATA and HEADERS frames' payload; for HEADERS - from the Decoder layer);
2. Layers DOWN flow order: TLS <- Framing <- Encoder <- Stream FSM.

###  Stream Priority/Dependencies
It seems that full featured scheduler for `TfwStreams` is needed for each `TfwCliConn` - called after Stream FSM (for UP and DOWN flows); maybe the base part of this functionality worth to implement in context of #309 and more specific logic leave for #1196; in this context, to generalize the current approach and HTTP/2 implementation, the possible variant may be to add into `TfwCliConn` - pointer to `TfwStreamSched` structure; for HTTP/2 should be the separate instance of it for each `TfwCliConn`, and for QUIC - there should be one global `TfwStreamSched` instance (to schedule Streams between all client connections); `TfwStreamSched instance` in turn can contain and maintain TfwStream instances according scheduling strategy:
1. For pure HTTP it can be just one `TfwStream` instance for one client connection without any scheduling; 2. For HTTP/2 at beginning (#309) there may be the base default scheduling logic - no dependencies and equal weights for Streams (i.e. all dependencies - on stream 0x0, and all weights equal 16: https://tools.ietf.org/html/rfc7540#section-5.3.5); in this case the transformed HTTP/1.1 requests must be sent to backends in order they came from TCP connection (with head-of-line blocking problem arised on server connections, but this cannot be avoided in HTTP/2 -> HTTP/1.1 proxy case); fields `parser`, `*msg`, `seq_queue` and `seq_qlock` must be moved from `TfwCliConn` to `TfwStream` (requests from `TfwStream.seq_queue` linked with `TfwSrvConn.fwd_queue` in usual way);
3. For full HTTP/2 Multiplexing support the scheduling based on `TfwStream's` dependency/priority must be implemented;
4. In case of QUIC - global `TfwStreamSched` may be used for scheduling (additional questions with synchronization and refcounting should be considered in this case).

### HTTP/2 layers implementation
Since `tfw_http_req_process()` is overloaded already and we need a lot of additional logic in it for HTTP/2 (Framing, Stream FSM, Stream Scheduler, Decoder), so to avoid additional complication and massive code copy-paste, in my opinion, `tfw_http_req_process()` should be splitted into two parts to reuse them from HTTP/1.1 and HTTP/2 contexts (from `__tfw_http_msg_process()`): the first part must be dependent on HTTP/1.1 or HTTP/2 contexts, and the second common part (scheduling, caching etc.) must remain almost unchanged; in this variant the layers ordering will have the following view:
1. TLS layer;
2. HTTP layer;
3. HTTP/2 or HTTP/1.1 protocol choice; in `__tfw_http_msg_process()` - atop of processing of skb chain, formed on TLS layer;
4. HTTP/2 Framing, Stream FSM, Stream Scheduler; collect skbs with HTTP/2 frames and pass them to the next layer with frame type; service frames are processed just right here;
5. `tfw_http_req_process()` for HTTP/2 instead of `tfw_http_parse_req()` from `ss_skb_process()` - calls assembling logic for request;
6. HTTP/2 request assembling layer; this layer is necessary since it seems that for HTTP/2 <-> HTTP/1.1 request transformation - we need to accumulate HTTP/2 frames (HEADERS, DATA, DATA, ..., HEADERS in context of particular Stream) - because headers should be concatenated with bodies for HTTP/1.1 (and, by the way, for responses we need to split HTTP/1.1 responses to form HTTP/2 separate HEADER and DATA frames, with creation of additional Streams); in future HTTP/2 <-> HTTP/2 proxy implementation, this layer should treat separate frames as requests; regarding received frame type this layer in turn calls HTTP/2 Decoder or HTTP parser;
7. HTTP/2 Decoder decodes HTTP/2 HEADERS frames and calls separate parts of splitted `tfw_http_parse_req()`; also allocations for new skbs will be needed on previous layer since decoded data is larger than original;
8. HTTP Parser.

### HTTP/2 over QUIC
In context of HTTP/2 features, which must be implemented, the main parts of future QUIC very rough architecture may be looked like:
1. New `sock.c` (for implementation QUIC Connections management, Congestion control and Loss recovery over UDP);
2. TLS layer;
3. Multistreaming management, which will be implemented inside HTTP/2 for separate connections, but can be scaled for system wide multiconnection support;
4. QPACK as scaled for multiconnection support HPACK;
5. HTTP/2 itself (over QUIC).

### Flow Control
It seems that we should implement at least WINDOW_UPDATE frame in #309 - in order to announce the largest possible window (second paragraph in https://tools.ietf.org/html/rfc7540#section-5.2.2).

**Comment by krizhanovsky** [comment]
Several comments:

> For pure HTTP it can be just one TfwStream instance for one client connection without any scheduling;

In HTTP/2 and HTTP/3 there are always 0th control stream, so probably it makes sense to embed `TfwStream` into `TfwCliConn` to save some allocations and pointer dereferences and make HTTP/1-compatibility logic simpler.

> HTTP/2 request assembling layer; this layer is necessary ....

How it's different from current assembling HTTP messages from ingress skb chunks? I'd expect that after decoding we can fail to our current messages processing logic.

> headers should be concatenated with bodies for HTTP/1.1

Not necessary. In #498 we exactly want to proxy message chunks as is. So probably in HTTP/2, when we assembled HTTP headers and can execute scheduling logic, we can proxy data frames w/o assembling. However, if it's simpler for now just to assemble whole messages - I'm fine with it. I'm only against introducing additional architectural layer which will be reworked in #498 - just don't want to do the same work twice.

Maybe the layer is required - I didn't actually get this

> in future HTTP/2 <-> HTTP/2 proxy implementation, this layer should treat separate frames as requests; regarding received frame type this layer in turn calls HTTP/2 Decoder or HTTP parser;

- why do we need the assembling layer for full HTTP/2 proxying?

> for responses we need to split HTTP/1.1 responses to form HTTP/2 separate HEADER and DATA frames, with creation of additional Streams

I think technically we can just insert two skb frames with appropriate HTTP/2 frame headers and, of course, update `TfwStream` state.

> can be the special flag for TfwCliConn which can be set during TLS ALPN procedure. ... Described variant does not use GFSM switching

Yes. GFSM is a generalization of hooks mechanism which allows several FSM to subscribe to a particular events and do context switches. FreeBSD netgraph uses similar approach for network protocols handling, but I don't think that it's an efficient way. Moreover, `TfwConn` may describe UDP flow for HTTP/3 in future.

> we should implement at least WINDOW_UPDATE frame in #309

Agree.

> It seems that for QUIC we must implement seperate Framing/StreamFSM/Scheduler) layer

The question is how much of the code we'll be able to reuse for HTTP/3. Now we only can keep HTTP/3 in mind during HTTP/2 development.

> QUIC Loss Recovery mechanism involves not only QUIC Connections layer, but also higher Framing layer too

I think the framing layer will provide downcalls plus to upcalls for HTTP/2, just the same way as current `connection.[ch]` provides hooks and normal function APIs.

> QUIC integrates TLS inward and this results in very closely intertwined interaction between QUIC Connections ... TLS handshakes must live atop of QUIC Frames

Yes, that's true. The only thing that we can do now is to separate framing layer as much as possible to be able to call it from the new UDP `sock.c` version. And the things aren't so bad - now we call TLS record creation exactly from TCP layer - we'll do very close things for HTTP/3. In #1031 we'll do more in this direction.

> three implementation variants for HTTP/2 and QUIC<->HTTP/3 could be specified

The 3rd variant is absolutely not an option. We'll definitely die if try to implement TCP/TLS/HTTP/2 concurrently with UDP/HTTP/3, especially given that the QUIC standard is constantly changing. Now we need to implement HTTP/2 ASAP and should only keep HTTP/3 in mind to choose more HTTP/3-friendly architecture if we have a choice. It'd be good if we can reuse the same logic, at least as a copy & paste foundation (e.g. we can copy some HTTP/2 framing logic and adjust it for HTTP/3). So I propose back to choosing between 1st and 2nd options when we have HTTP/2 and start with #724 .

**Comment by krizhanovsky** [comment]
Minutes from the conversation:

1. `tfw_http_adjust_resp()` can and shall convert HTTP/1.1 to HTTP/2 headers **in-place** since we don't use Huffman encoding and HPACK is always shorter than original text headers. This is different with `tfw_http_adjust_req()` which should allocate a new memory to convert HTTP/2 packed headers to HTTP/1.1.

**Comment by aleksostapenko** [comment]
General scope distribution, with separate Pull Request (checkboxes) for each subtask:
### Base functionality
- [ ] **Framing (PR)**
   Frames: HEADERS, DATA, CONTINUATION, RST_STREAM, PING, SETTINGS, GOAWAY and WINDOW_UPDATE;
   1. Receiving skbs with HTTP/2 Frames and passing them to the next layer (after processing in Stream Scheduler and Stream FSM);
   2. Management logic for the whole connection state (RST_STREAM, PING, SETTINGS, GOAWAY and WINDOW_UPDATE) with help of corresponding interfaces of Stream Scheduler and Stream FSM, including:
      a) Processing service Frames, prepare and send response Frames for them;
      b) Receiving, parsing the client preface and sending server preface (SETTINGS Frame).

- [ ] **Starting/switching HTTP/2 (PR)**
  1. Corresponding changes in our TLS layer for ALPN ('ttls_parse_alpn_ext()' etc.);
  2. Configuration support for HTTP/2 and corresponding changes in HTTP layer;
  3. Switching into HTTP/2 inside Tempesta HTTP layer.

### Streams
- [ ] **Stream Scheduler (PR)**
   Implementation of minimal base logic (for equal Streams priorities and no dependencies) and interfaces; the rest will be implemented in #1196.
- [ ] **Disable @seq_queue for HTTP/2 (PR)**
- [ ] **Stream FSM (PR)**

### Messages' transformation HTTP/2-HTTP/1.1
- [ ] **Request HTTP/2 -> HTTP/1.1 (PR)**
   1. Coalesce HTTP/2 Frames HEADERS-DATA-HEADERS into the one data chunk;
   2. Transformation of coalesced HEADERS-DATA-HEADERS data into HTTP/1.1 request - in 'tfw_http_adjust_req()';
   3. Changings in current chunked, Content-Length and connection close logic, since HTTP/2 defines message length in other ways than HTTP/1.1.
- [ ] **Response HTTP/1.1 -> HTTP/2 (PR)**
   1. In-place Frames packing: HEADERS and DATA;
   2. TLS (completed) <- In-place Frames packing <- HPACK Encoder <- Stream FSM (must be completed)
      ('Framing (pack)' and 'HPACK Encoder' interfaces must be called inside 'tfw_http_adjust_resp()').

### HPACK
- [ ] **Refactoring and integration of HPACK code from #1176 (PR)**
   1. Static table
   2. Dynamic table
   3. HPACK decoder
   4. HPACK encoder (without Huffman)
- [ ] **Splitting of HTTP parser and corresponding changes (PR)**

**Comment by krizhanovsky** [comment]
@aleksostapenko please by the end of development learn performance profile of the HTTP/2 implementation on small (like 1-8 bytes) cached content and compare it with HTTP/1.1 over TLS. Before closing the task we must be sure that HTTP/2 at least not worse than HTTP/1.1 in performance.

**Comment by krizhanovsky** [comment]
Done in #1368
